version: "3.8"

services:
  mongo:
    image: mongo:6
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: nazmer-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/nazmer
      - JWT_SECRET=yourSuperSecretKey123
      - JWT_EXPIRE=7d
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: nazmer-frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://68.210.104.118:5000
    depends_on:
      - backend

volumes:
  mongo_data:
